version: "2"
services: # storage
  storage:
    image: storage
    ports:
      - 8082:8082
    networks:
      - network1

  # receiver
  receiver:
    image: receiver
    ports:
      - 8080:8080
    networks:
      - network1

networks:
  network1:
    name: lab4_default
    external: true

volumes:
  data:
